language: ruby
rvm:
  - 2.2.0
sudo: false
cache: bundler
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database myflix_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
script:
  - "bundle exec rake knapsack:rspec"
env:
  global:
    - STRIPE_PUBLIC_KEY=pk_test_6ExTnyy4VVEosXe4wc9WFm49
    - STRIPE_API_KEY=sk_test_NBqYrblkJ00RufJgPAUFLPdA
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
