language: ruby
rvm:
  - 2.1.0
sudo: false
cache: bundler
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database myflix_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
script: bundle exec rspec spec
env:
  STRIPE_PUBLIC_KEY=pk_test_6ExTnyy4VVEosXe4wc9WFm49
  STRIPE_API_KEY=sk_test_NBqYrblkJ00RufJgPAUFLPdA
